In [1]:
import numpy as np

In [2]:
a = np.empty((4,4), dtype=int)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [3]:
b = np.ones((4,4), dtype=int)
print(b)

c = np.ones(5)
print(c)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[1. 1. 1. 1. 1.]


In [4]:
d = np.zeros(4)
d

array([0., 0., 0., 0.])

In [5]:
e = np.ones((4,8), dtype=bool)
print(e)

f = np.zeros((4,8), dtype=bool)
print(f)

[[ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]]
[[False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]]
