In [1]:
import numpy as np

In [ ]:
a = np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [3]:
a=np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [5]:
a = np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
a = a.reshape((3,3))
# c = np.array(a).  same output
c

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
a = a.flatten().  #Returns a copy.   Uses more memory (copy).    Independent from original
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
b = a.ravel()   #Returns a view (if possible).    ✅ Might reflect changes in the original. More memory-efficient.   Can affect original (if view)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])