In [2]:
import numpy as np

In [3]:
lst = [1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [12]:
print('1D array') 
a= np.array([1,2,3,4,5]) #np.array is used for create numpy array from tuple/list or other array like structure
print(a)

1D array
[1 2 3 4 5]


In [5]:
print('2D array')
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)


print('3D array')
c = np.array([[[1,2,3], [4,5,6] ,[7,8,9]]])
print(c)

2D array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3D array
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [15]:
type(a)
type(lst)
type(a)

numpy.ndarray

In [ ]:
print(a.size)
print(b.size)
print(c.size)

# size of array or number of elements in array


5
10
9


In [30]:
print(a.shape)
print(b.shape)
print(c.shape)

# shape = (rows, cols)

(5,)
(2, 5)
(1, 3, 3)


In [33]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


In [34]:
c.transpose()

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])